// auth
export const AUTH_USER = "AUTH_USER";
export const DEAUTH_USER = "DEAUTH_USER";
export const AUTH_ERROR = "AUTH_ERROR";
export const SIGN_UP_USER = "SIGN_UP_USER";
export const REMIND_PASSWORD = "REMIND_PASSWORD";
export const REMIND_PASSWORD_ERROR = "REMIND_PASSWORD_ERROR";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const SIGN_UP_ERROR = "SIGN_UP_ERROR";

// chat
export const NEW_MESSAGE = "NEW_MESSAGE";
export const OUTCOMING_MESSAGE = "OUTCOMING_MESSAGE";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const RECEIVE_MESSAGE = "RECEIVE_MESSAGE";
export const GET_CHATS = "GET_CHATS";
export const GET_CHATS_ERROR = "GET_CHATS_ERROR";
export const GET_MESSAGES = "GET_MESSAGES";
export const GET_MESSAGES_ERROR = "GET_MESSAGES_ERROR";
export const SET_ACTIVE_CHAT = "SET_ACTIVE_CHAT";
