// auth
export const AUTH_USER = "AUTH_USER";
export const DEAUTH_USER = "DEAUTH_USER";
export const AUTH_ERROR = "AUTH_ERROR";
export const SIGN_UP_USER = "SIGN_UP_USER";
export const REMIND_PASSWORD = "REMIND_PASSWORD";
export const REMIND_PASSWORD_ERROR = "REMIND_PASSWORD_ERROR";
export const CHANGE_PASSWORD = "CHANGE_PASSWORD";
export const SIGN_UP_ERROR = "SIGN_UP_ERROR";
export const CHANGE_USER_SETTINGS = "CHANGE_USER_SETTINGS";
export const FIND_USERS = "FIND_USERS";

// chat
export const NEW_MESSAGE = "NEW_MESSAGE";
export const OUTCOMING_MESSAGE = "OUTCOMING_MESSAGE";
export const SEND_MESSAGE = "SEND_MESSAGE";
export const RECEIVE_MESSAGE = "RECEIVE_MESSAGE";
export const GET_CHATS = "GET_CHATS";
export const GET_CHATS_ERROR = "GET_CHATS_ERROR";
export const GET_MESSAGES = "GET_MESSAGES";
export const GET_MESSAGES_ERROR = "GET_MESSAGES_ERROR";
export const SET_ACTIVE_CHAT = "SET_ACTIVE_CHAT";
export const ADD_USER_TO_CHAT_LOCALY = "ADD_USER_TO_CHAT_LOCALY";
export const DELETE_USER_FROM_CHAT_LOCALY = "DELETE_USER_FROM_CHAT_LOCALY";
export const CREATE_NEW_CHAT = "CREATE_NEW_CHAT";
export const DELETE_ALL_USERS_FROM_CHAT_LOCALY = "DELETE_ALL_USERS_FROM_CHAT_LOCALY";
export const UPDATE_CHAT = "UPDATE_CHAT";
export const UPLOAD_PROGRESS = "UPLOAD_PROGRESS";
export const UPLOAD_START = "UPLOAD_START";
export const UPLOAD_END = "UPLOAD_END";
export const REFRESH_CHATLIST_START = "REFRESH_CHATLIST_START";
export const REFRESH_CHATLIST_END = "REFRESH_CHATLIST_END";
export const GET_CHATLIST_TIMESTAMP = "GET_CHATLIST_TIMESTAMP";
export const ADD_PICTURE_IN_MESSAGE_LOCALY = "ADD_PICTURE_IN_MESSAGE_LOCALY";
export const DELETE_PICTURE_IN_MESSAGE_LOCALY = "DELETE_PICTURE_IN_MESSAGE_LOCALY";
export const CLEAN_PICTURE_IN_MESSAGE_LOCALY = "CLEAN_PICTURE_IN_MESSAGE_LOCALY";
