# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NativeStarterKit' do
  pod 'AppCenter/Crashes', '~> 1.9.0'
  pod 'AppCenter/Analytics', '~> 1.9.0'
  pod 'AppCenterReactNativeShared', '~> 1.8.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NativeStarterKit

  

  platform :ios, '9.0'
  target 'NativeStarterKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'NativeStarterKit-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for NativeStarterKit-tvOS

  target 'NativeStarterKit-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
